### ISSUE TITLE
Any suggestions on speeding up training?

### ISSUE THREAD

**Issue by WangYixuan12** [real-stanford/diffusion_policy#23]
Hi Cheng, this work is incredible and elegant! I tried the code, and I found that the training time for each task and method is around 12 hrs. I am also testing on the robomimic can task, and it seems to take a while to get a performant policy. I am wondering whether you have any suggestions for speeding up the training process.

**Comment by cheng-chi** [comment]
Hi @WangYixuan12,
   12 hrs training time sounds about right! If you need futher training acceleration, you can try to:
1. reduce the number of training diffusion iterations (e.g. 50 or 25)
2. reduce the frequency of simluation rollouts evaluations (they are very slow and can sometimes take more time than training)
3. try improving policy runtime using [torch.compile](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html)

**Comment by WangYixuan12** [comment]
Thank you for your helpful tips! I will try them.
