### ISSUE TITLE
How to generate low dim embeddings the for Kitchen Envs

### ISSUE THREAD

**Issue by xavihart** [real-stanford/diffusion_policy#25]
In the dataset, the observation sequence is sized N*60, is there any code snippets to generate the low dim embeddings?

**Comment by cheng-chi** [comment]
Hi @xavihart I'm not quite sure I understand your question. The native observation space for the kitchen task is 60 (though a lot of these dimensions are empty), and the dataset is directly extracted from [*.mjl files](https://github.com/google-research/relay-policy-learning/blob/master/kitchen_demos_multitask.zip) published in the original [relay-policy-learining repo](https://github.com/google-research/relay-policy-learning) inside [KitchenMjlLowdimDataset](https://github.com/real-stanford/diffusion_policy/blob/548a52bbb105518058e27bf34dcf90bf6f73681a/diffusion_policy/dataset/kitchen_mjl_lowdim_dataset.py#L37)

**Comment by xavihart** [comment]
I got it, so it is not vision-based?

**Comment by cheng-chi** [comment]
Yes, we only have state-based version of the kitchen task in this repo.
