### ISSUE TITLE
Question regarding real-world experiment dataflow design

### ISSUE THREAD

**Issue by WangYixuan12** [real-stanford/diffusion_policy#31]
Hi Cheng, I found that in `demo_real_robot.py`, you sync data from different sources manually, instead of using ROS. Also, multiple realsense cameras are handled by yourself instead of multiple ROS nodes. Is there any reason behind this design?

**Comment by cheng-chi** [comment]
Hi @WangYixuan12, I never compared with ROS-based solutions for camera handeling. However, I believe my current shared-memory based method for passing images will have less overhead and latency than ROS by avoiding mutlitple copies in the OS networking stack. In general, I try to avoid depending on ROS as much as possible to avoid its messy OS-wide dependency management, custom C++ focused build system and frangmented community (split between ROS and ROS 2).

**Comment by WangYixuan12** [comment]
Got it! Thank you for the explanation!
