### ISSUE TITLE
Relative or Absolute Actions

### ISSUE THREAD

**Issue by andrearosasco** [real-stanford/diffusion_policy#70]
Hello, I've seen that for the robomimic dataset you provide trajectories both with relative and absolute actions. 
I was wondering which ones were used for the experiments in the paper and why?

Also, are the actions in those trajectories cartesian? If so, when do you convert them to joints?

Thanks for the great work

Edit: ok apparently the actions are absolute, still not sure when they are converted to joint space. Also, why in the yaml config for e.g. lift, action.shape is 10?

Edit: ok I was confused by position and velocity control and thought it meant your action space was qpos and qvel but apparently the actions are still cartesian. I guees action.shape = 10 is the chunk size.

Closing

**Comment by yukaryote** [comment]
Hi, I was also curious about this. Where is it said that the action space is the 3D pose, 6D rotation, and binary open/close value of the gripper?
